# Generated by Django 4.0.6 on 2022-09-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='The contributor first name. ', max_length=200)),
                ('last_name', models.CharField(help_text='The contributor last name. ', max_length=200)),
                ('email', models.EmailField(help_text=' The contact email for the contributor. ', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MovieContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director')], max_length=20, verbose_name='The role this contributor had in the Movie. ')),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieslistapp.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of thePublisher. ', max_length=200)),
                ('website', models.URLField(help_text=" The publisher's website. ")),
                ('email', models.EmailField(help_text=" The publisher's email address. ", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The Review text. ')),
                ('rating', models.IntegerField(help_text='The rating the review has given. ')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='the date and time review was created. ')),
            ],
        ),
        migrations.CreateModel(
            name='MoviesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Movie. ', max_length=200)),
                ('date', models.DateField(verbose_name='Date of The Movie was released. ')),
                ('contributors', models.ManyToManyField(through='Movieslistapp.MovieContributor', to='Movieslistapp.contributor')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieslistapp.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='moviecontributor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieslistapp.moviesinfo'),
        ),
    ]
