# Generated by Django 4.0.6 on 2022-09-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_name', models.CharField(max_length=200)),
                ('movies_date', models.DateField(verbose_name='Date of a delivery')),
            ],
        ),
    ]
