# Generated by Django 4.0.6 on 2022-09-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movieslistapp', '0002_review_creator_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(help_text='the movies that this review is for. ', on_delete=django.db.models.deletion.CASCADE, to='Movieslistapp.moviesinfo'),
        ),
    ]
